# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
            - name: ssh-scp-ssh-pipelines
  # You may pin to the exact commit or the version.
  # uses: cross-the-world/ssh-scp-ssh-pipelines@78e864b4890087a58248ff39320406971ca88b89
  uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
  with:
    # ssh remote host
    host: 
    # ssh remote port
    port: # optional, default is 22
    # ssh remote user
    user: 
    # content of ssh private key. ex raw content of ~/.ssh/id_rsa
    key: # optional
    # ssh remote password
    pass: # optional
    # connection timeout to remote host
    connect_timeout: # optional, default is 30s
    # execute pre-commands before scp
    first_ssh: # optional
    # scp from local to remote
    scp: # optional
    # execute post-commands after scp
    last_ssh: # optional
          
